# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/cubits/*.dart
          - lib/models/*.dart
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true # changed
          field_rename: snake # changed
          ignore_unannotated: false
          include_if_null: true
