name: pet_finder
description: We love cats!

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  google_fonts: ^2.1.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0

  copy_with_extension: ^3.0.0
  json_annotation: ^4.4.0
  equatable: ^2.0.3
  recase: ^4.0.0
  enum_to_string: ^2.0.1
  gql: ^0.13.0
  graphql: ^5.0.0 # ^3.1.0

  path_provider: ^2.0.8
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0

  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1

  bot_toast: ^4.0.1 # TODO: есть какая-то замена в обновлённом Material
  # validators: ^3.0.0
  image_picker: ^0.8.4+4
  rainbow_color: ^2.0.1
  extended_image: ^6.0.1
  uuid: ^3.0.5
  crypto: ^3.0.1
  # flutter_image_compress ^1.1.0 # TODO: прикрутить вместо image_picker - как unix-way
  scrollable_positioned_list: ^0.2.3

  formz: ^0.4.1 # TODO: выпилить вместе с моделями *InputModel

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.8.1

  build_runner: ^2.1.7
  copy_with_extension_gen: ^3.0.0
  json_serializable: ^6.1.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/vets/
    - assets/images/cats/
    - assets/images/dogs/
    - assets/images/hamsters/
    - assets/images/bunnies/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
