// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT4se59PhQ_DyRi34gHZmQkgBOi6Qk8yo',
    appId: '1:62035848148:web:522d037b15288d42088441',
    messagingSenderId: '62035848148',
    projectId: 'pet-finder-1703',
    authDomain: 'pet-finder-1703.firebaseapp.com',
    storageBucket: 'pet-finder-1703.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKxtyUaWCbMSGr3jw0jhFEArKkCx84Sc',
    // appId: '1:62035848148:android:bbe8412c349164f2088441',
    appId: '1:62035848148:android:18725c558dccc36e088441',
    messagingSenderId: '62035848148',
    projectId: 'pet-finder-1703',
    storageBucket: 'pet-finder-1703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4c2ztfJNfW2cFeFRHzOieK6LKtq0La38',
    appId: '1:62035848148:ios:aa294559e86cf92c088441',
    messagingSenderId: '62035848148',
    projectId: 'pet-finder-1703',
    storageBucket: 'pet-finder-1703.appspot.com',
    iosClientId:
        '62035848148-4tp9na6svenb332on2254hvor5grj8pk.apps.googleusercontent.com',
    iosBundleId: 'com.arisesoft.pet-finder-1703',
  );
}
